version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    environment:
      TZ: 'Asia/Jakarta'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/docker/volumes/pihole/etc-pihole/:/etc/pihole/'
      - '/opt/docker/volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '/opt/docker/volumes/pihole/var-log/:/var/log'
      - '/opt/docker/volumes/pihole/etc-cont-init.d/10-fixroutes.sh:/etc/cont-init.d/10-fixroutes.sh'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    networks:
      internal:
      lan:
        ipv4_address: 192.168.1.10

networks:
  internal:
  lan:
    name: lan
    driver: macvlan
    driver_opts:
      parent: br-lan.20
    ipam:
      config:
        - subnet: 192.168.1.0/24
